-- Migration unit 1: schema_changes
-- Transaction mode: transactional
-- Boundary reason: default

CREATE TABLE public.oauth_accounts (
  id               bigint                      GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id          bigint                      NOT NULL,
  provider         character varying           NOT NULL,
  provider_user_id character varying           NOT NULL,
  access_token     character varying,
  refresh_token    character varying,
  token_expires_at timestamp without time zone,
  created_at       timestamp without time zone NOT NULL
);

ALTER TABLE public.oauth_accounts
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.oauth_accounts
  ADD CONSTRAINT oauth_accounts_pkey PRIMARY KEY (id);

ALTER TABLE public.oauth_accounts
  ADD CONSTRAINT oauth_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."User"(id) ON DELETE CASCADE;

GRANT ALL ON public.oauth_accounts TO anon;

GRANT ALL ON public.oauth_accounts TO authenticated;

GRANT ALL ON public.oauth_accounts TO service_role;
