-- Migration unit 1: schema_changes
-- Transaction mode: transactional
-- Boundary reason: default

DROP EXTENSION pg_net;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO service_role;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO service_role;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO service_role;

CREATE TABLE public."Categories" (
  id          bigint            GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name        character varying NOT NULL,
  slug        character varying NOT NULL,
  description text,
  parent_id   bigint
);

COMMENT ON TABLE public."Categories" IS 'Categories';

ALTER TABLE public."Categories"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public."Categories"
  ADD CONSTRAINT "Categories_pkey" PRIMARY KEY (id);

ALTER TABLE public."Categories"
  ADD CONSTRAINT "Categories_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES public."Categories"(id);

ALTER TABLE public."Categories"
  ADD CONSTRAINT "Categories_slug_key" UNIQUE (slug);

GRANT ALL ON public."Categories" TO anon;

GRANT ALL ON public."Categories" TO authenticated;

GRANT ALL ON public."Categories" TO service_role;

CREATE TABLE public."Post_tags" (
  post_id bigint NOT NULL,
  tag_id  bigint NOT NULL
);

COMMENT ON TABLE public."Post_tags" IS '.';

ALTER TABLE public."Post_tags"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public."Post_tags"
  ADD CONSTRAINT "Post_tags_pkey" PRIMARY KEY (post_id, tag_id);

GRANT ALL ON public."Post_tags" TO anon;

GRANT ALL ON public."Post_tags" TO authenticated;

GRANT ALL ON public."Post_tags" TO service_role;

CREATE TABLE public."Tags" (
  id   bigint            GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name character varying NOT NULL,
  slug character varying NOT NULL
);

COMMENT ON TABLE public."Tags" IS '.';

ALTER TABLE public."Tags"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public."Tags"
  ADD CONSTRAINT "Tags_name_key" UNIQUE (name);

ALTER TABLE public."Tags"
  ADD CONSTRAINT "Tags_pkey" PRIMARY KEY (id);

ALTER TABLE public."Post_tags"
  ADD CONSTRAINT "Post_tags_tag_id_fkey" FOREIGN KEY (tag_id) REFERENCES public."Tags"(id) ON DELETE CASCADE;

ALTER TABLE public."Tags"
  ADD CONSTRAINT "Tags_slug_key" UNIQUE (slug);

GRANT ALL ON public."Tags" TO anon;

GRANT ALL ON public."Tags" TO authenticated;

GRANT ALL ON public."Tags" TO service_role;

CREATE TABLE public."User" (
  id            bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  username      character varying        NOT NULL,
  email         character varying        NOT NULL,
  password_hash character varying        NOT NULL,
  avatar_url    character varying,
  bio           text,
  role          character varying        DEFAULT 'user'::character varying NOT NULL,
  created_at    timestamp with time zone NOT NULL
);

COMMENT ON TABLE public."User" IS 'User description';

ALTER TABLE public."User"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public."User"
  ADD CONSTRAINT "User_email_key" UNIQUE (email);

ALTER TABLE public."User"
  ADD CONSTRAINT "User_pkey" PRIMARY KEY (id);

ALTER TABLE public."User"
  ADD CONSTRAINT "User_username_key" UNIQUE (username);

GRANT ALL ON public."User" TO anon;

GRANT ALL ON public."User" TO authenticated;

GRANT ALL ON public."User" TO service_role;

CREATE TABLE public."Votes" (
  id           bigint            GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id      bigint            NOT NULL,
  votable_type character varying NOT NULL,
  votable_id   character varying NOT NULL,
  value        integer           NOT NULL
);

COMMENT ON TABLE public."Votes" IS 'Votes ma boi';

ALTER TABLE public."Votes"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public."Votes"
  ADD CONSTRAINT "Votes_pkey" PRIMARY KEY (id);

ALTER TABLE public."Votes"
  ADD CONSTRAINT "Votes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."User"(id);

ALTER TABLE public."Votes"
  ADD CONSTRAINT "Votes_user_id_key" UNIQUE (user_id);

ALTER TABLE public."Votes"
  ADD CONSTRAINT "Votes_votable_id_key" UNIQUE (votable_id);

ALTER TABLE public."Votes"
  ADD CONSTRAINT "Votes_votable_type_key" UNIQUE (votable_type);

GRANT ALL ON public."Votes" TO anon;

GRANT ALL ON public."Votes" TO authenticated;

GRANT ALL ON public."Votes" TO service_role;

CREATE TABLE public.comments (
  id                bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  post_id           bigint                   NOT NULL,
  user_id           bigint                   NOT NULL,
  parent_comment_id bigint                   NOT NULL,
  body              character varying,
  created_at        timestamp with time zone DEFAULT now() NOT NULL,
  updated_at        timestamp with time zone
);

COMMENT ON TABLE public.comments IS 'post discussions';

ALTER TABLE public.comments
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.comments
  ADD CONSTRAINT comments_parent_comment_id_key UNIQUE (parent_comment_id);

ALTER TABLE public.comments
  ADD CONSTRAINT comments_pkey PRIMARY KEY (id);

ALTER TABLE public.comments
  ADD CONSTRAINT comments_parent_comment_id_fkey FOREIGN KEY (parent_comment_id) REFERENCES public.comments(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE public.comments
  ADD CONSTRAINT comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."User"(id) ON UPDATE CASCADE ON DELETE RESTRICT;

GRANT ALL ON public.comments TO anon;

GRANT ALL ON public.comments TO authenticated;

GRANT ALL ON public.comments TO service_role;

CREATE TABLE public.posts (
  id          bigint                   NOT NULL,
  user_id     bigint                   NOT NULL,
  category_id bigint                   NOT NULL,
  title       character varying,
  body        text,
  view_count  integer,
  is_pinned   boolean,
  is_locked   boolean,
  created_at  timestamp with time zone DEFAULT now() NOT NULL,
  updated_at  timestamp with time zone
);

ALTER TABLE public.posts
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.posts
  ADD CONSTRAINT posts_category_id_fkey FOREIGN KEY (category_id) REFERENCES public."Categories"(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE public.posts
  ADD CONSTRAINT posts_pkey PRIMARY KEY (id);

ALTER TABLE public."Post_tags"
  ADD CONSTRAINT "Post_tags_post_id_fkey" FOREIGN KEY (post_id) REFERENCES public.posts(id) ON DELETE CASCADE;

ALTER TABLE public.comments
  ADD CONSTRAINT comments_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE public.posts
  ADD CONSTRAINT posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."User"(id) ON UPDATE CASCADE ON DELETE RESTRICT;

GRANT ALL ON public.posts TO anon;

GRANT ALL ON public.posts TO authenticated;

GRANT ALL ON public.posts TO service_role;
